# example netlify.toml
[build]
  command = "eleventy"
  functions = "netlify/functions"
  publish = "public"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
