# example netlify.toml
[build]
  command = "eleventy"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "./public/img/", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]